import { useState, useEffect, useRef } from "react";
import { jsPDF } from "jspdf"; // Added for real PDF generation
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { 
  Send, Paperclip, Phone, Video, MoreHorizontal,
  Clock, CheckCircle2, FileText, Image, ChevronRight,
  ExternalLink, Home, Users, BookOpen, Heart, ShoppingBag, Bell, User,
  CheckCircle, Calendar, MapPin
} from "lucide-react";

// --- Types ---
interface Message {
  id: string;
  sender: "doctor" | "patient" | "system";
  content: string;
  timestamp: Date;
  type: "text" | "image" | "file";
  isRead: boolean;
}

interface Booking {
  id: string;
  doctorName: string;
  specialty: string;
  patientName: string;
  location: string;
  time: string;
  date: string;
  fee: string;
}

const Consultation = () => {
  // --- DATABASE STATES ---
  const [isCompleted, setIsCompleted] = useState(false);
  
  const [currentBooking, setCurrentBooking] = useState<Booking>({
    id: "59pLZWyZMweacFqmkueB",
    doctorName: "Dr. Emily Rodriguez",
    specialty: "Pediatrics",
    patientName: "poojaa",
    location: "Children's Hospital",
    time: "2:30 PM",
    date: "2026-01-02",
    fee: "₹1,245" 
  });

  const nextBookingData: Booking = {
    id: "BK-NEXT-01",
    doctorName: "Dr. Emily Rodriguez",
    specialty: "Pediatric Follow-up",
    patientName: "poojaa",
    location: "Children's Hospital",
    time: "10:00 AM",
    date: "2026-01-15",
    fee: "₹800"
  };

  const [message, setMessage] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const [duration, setDuration] = useState(0); 
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "1",
      sender: "doctor",
      content: `Good afternoon, ${currentBooking.patientName}. I am the HealthSync AI Assistant for ${currentBooking.doctorName}. Our session at ${currentBooking.location} is active. How can I assist you today?`,
      timestamp: new Date(Date.now() - 5 * 60 * 1000),
      type: "text",
      isRead: true,
    }
  ]);

  const messagesEndRef = useRef<HTMLDivElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (!isCompleted) {
      const timer = setInterval(() => setDuration(prev => prev + 1), 60000); 
      return () => clearInterval(timer);
    }
  }, [isCompleted]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isTyping]);

  // --- PDF GENERATION LOGIC ---
  const generateClinicalPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header Style
    doc.setFillColor(20, 184, 166); // Teal color
    doc.rect(0, 0, pageWidth, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("Clinical Consultation Summary", 20, 25);
    
    // Body Text Style
    doc.setTextColor(40, 40, 40);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    
    // Details Section
    doc.text(`Booking ID: ${currentBooking.id}`, 20, 55);
    doc.text(`Date: ${currentBooking.date}`, 20, 62);
    doc.text(`Patient: ${currentBooking.patientName}`, 20, 69);
    doc.text(`Doctor: ${currentBooking.doctorName} (${currentBooking.specialty})`, 20, 76);
    
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 85, pageWidth - 20, 85);
    
    // Summary Section
    doc.setFont("helvetica", "bold");
    doc.text("Clinical Notes & Summary:", 20, 95);
    
    doc.setFont("helvetica", "normal");
    const systemMsg = messages.find(m => m.sender === "system")?.content || "General check-up completed.";
    const splitText = doc.splitTextToSize(systemMsg, pageWidth - 40);
    doc.text(splitText, 20, 105);

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by HealthSync AI • Verified Digital Record", pageWidth / 2, 280, { align: 'center' });

    doc.save(`Summary_${currentBooking.id.substring(0, 8)}.pdf`);
  };

  const handleStartNextConsultation = () => {
    setCurrentBooking(nextBookingData);
    setIsCompleted(false);
    setDuration(0);
    setMessages([{
      id: Date.now().toString(),
      sender: "doctor",
      content: `Hello ${nextBookingData.patientName}, we are now starting your follow-up session for ${nextBookingData.specialty}. I've retrieved your records from the Jan 2nd visit. How are you feeling today?`,
      timestamp: new Date(),
      type: "text",
      isRead: true,
    }]);
  };

  const handleEndConsultation = () => {
    setIsCompleted(true);
    
    const symptoms: string[] = [];
    const files: string[] = [];
    let requestedPrescription = false;

    messages.forEach(msg => {
      const text = msg.content.toLowerCase();
      if (msg.sender === "patient") {
        if (text.includes("headache") || text.includes("head ache")) symptoms.push("Headache");
        if (text.includes("fever") || text.includes("temperature")) symptoms.push("Fever");
        if (text.includes("pain") || text.includes("hurt")) symptoms.push("Pain");
        if (text.includes("cough") || text.includes("cold")) symptoms.push("Cough/Cold");
        if (text.includes("uploaded image")) files.push(msg.content.split(": ")[1] || "Image Attachment");
        if (text.includes("prescription")) requestedPrescription = true;
      }
    });

    const symptomList = symptoms.length > 0 ? symptoms.join(", ") : "General Consultation";
    const fileList = files.length > 0 ? `\nAttachments: ${files.join(", ")}` : "";
    const rxStatus = requestedPrescription ? "\nPrescription: Requested" : "";

    const summaryContent = `CONSULTATION ENDED\n\n--- CLINICAL SUMMARY ---\nDetected Symptoms: ${symptomList}${fileList}${rxStatus}\n\nYour summary is ready for download. Your next appointment is now prioritized below.`;

    const endMsg: Message = {
      id: `sys-${Date.now()}`,
      sender: "system",
      content: summaryContent,
      timestamp: new Date(),
      type: "text",
      isRead: true,
    };
    setMessages(prev => [...prev, endMsg]);
  };

  const simulateAIResponse = (patientText: string, context: "general" | "upload" | "history" | "prescription" = "general") => {
    if (isCompleted) return;
    setIsTyping(true);

    setTimeout(() => {
      let responseContent = "";
      const lowerText = patientText.toLowerCase();

      if (context === "upload") {
        responseContent = "I've received your file. I'll make sure Dr. Rodriguez reviews it before the session.";
      } else if (context === "history") {
        responseContent = "Thank you. I'm syncing your medical history with your current profile for the doctor.";
      } else if (context === "prescription") {
        responseContent = "I've logged your request for a prescription. The doctor will review this shortly.";
      } 
      else if (lowerText.includes("pain") || lowerText.includes("hurt")) {
        responseContent = "I'm sorry to hear you're in pain. Can you tell me on a scale of 1-10 how severe it is, or if it's constant?";
      } else if (lowerText.includes("fever") || lowerText.includes("temperature") || lowerText.includes("hot")) {
        responseContent = "I've noted the fever. Have you checked your temperature with a thermometer recently?";
      } else if (lowerText.includes("cough") || lowerText.includes("cold") || lowerText.includes("throat")) {
        responseContent = "I see. Are you experiencing any difficulty breathing or is it mainly a sore throat?";
      } else if (lowerText.includes("hello") || lowerText.includes("hi")) {
        responseContent = `Hello! I'm here to help gather details for ${currentBooking.doctorName}. What symptoms are we looking at today?`;
      }
      else {
        responseContent = "I've shared that detail with the doctor's team. Is there any other symptom you'd like to mention?";
      }

      const aiMessage: Message = {
        id: Date.now().toString(),
        sender: "doctor",
        content: responseContent,
        timestamp: new Date(),
        type: "text",
        isRead: false,
      };

      setMessages((prev) => [...prev, aiMessage]);
      setIsTyping(false);
    }, 1500);
  };

  const sendMessage = (e?: React.FormEvent, customText?: string) => {
    if (e) e.preventDefault();
    const finalMsg = customText || message;
    if (!finalMsg.trim() || isCompleted) return;

    const newMessage: Message = {
      id: Date.now().toString(),
      sender: "patient",
      content: finalMsg,
      timestamp: new Date(),
      type: "text",
      isRead: false,
    };

    setMessages((prev) => [...prev, newMessage]);
    
    if (!customText) {
      simulateAIResponse(finalMsg, "general");
      setMessage("");
    }
  };

  const handleQuickAction = (action: string) => {
    if (isCompleted) {
      if (action === "Download Summary") {
        generateClinicalPDF(); // Calling the real function
      }
      if (action === "View Clinical Notes") alert("Accessing secure records...");
      return;
    }

    switch(action) {
      case "Share Medical History":
        const historyMsg = "I'm sharing my medical history and previous reports for your review.";
        sendMessage(undefined, historyMsg);
        simulateAIResponse(historyMsg, "history");
        break;
      case "Upload Images":
        fileInputRef.current?.click();
        break;
      case "Request Prescription":
        const rxMsg = "I would like to request a prescription based on the symptoms we've discussed.";
        sendMessage(undefined, rxMsg);
        simulateAIResponse(rxMsg, "prescription");
        break;
      default:
        break;
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const newMessage: Message = {
        id: Date.now().toString(),
        sender: "patient",
        content: `Uploaded image: ${file.name}`,
        timestamp: new Date(),
        type: "file",
        isRead: false,
      };
      setMessages(prev => [...prev, newMessage]);
      simulateAIResponse(file.name, "upload");
    }
  };

  const formatTime = (date: Date) => {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }).toLowerCase();
  };

  return (
    <div className="h-screen relative flex flex-col font-sans overflow-hidden">
      
      {/* PROFESSIONAL BACKGROUND IMAGE LAYER */}
      <div 
        className="fixed inset-0 z-0"
        style={{
          backgroundImage: `url(https://th.bing.com/th/id/OIP.jEIorB3Kbxka1-dkG2oLTwHaDF?w=306&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3)`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
        }}
      >
        <div className="absolute inset-0 bg-slate-900/45 backdrop-blur-[3px]" />
      </div>

      <nav className="h-16 bg-white/80 backdrop-blur-md border-b flex items-center justify-between px-8 shrink-0 z-20">
        <div className="flex items-center space-x-10">
          <div className="flex-1 flex items-centre justify-center space-x-5 text-teal-600 font-bold text-xl cursor-pointer">
          </div>
        </div>
      </nav>

      <main className="flex-1 flex overflow-hidden max-w-[1600px] mx-auto w-full z-10">
        {/* Chat Interface */}
        <div className="flex-1 flex flex-col bg-white/60 backdrop-blur-xl shadow-sm border-x border-slate-200/50">
          <div className="p-4 border-b flex justify-between items-center bg-white/40 backdrop-blur-md sticky top-0 z-10">
            <div className="flex items-center space-x-4">
              <div className="relative">
                <img src="https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=300" className="w-12 h-12 rounded-full object-cover border-2 border-white shadow-sm" alt="" />
                <div className={`absolute bottom-0 right-0 w-3.5 h-3.5 ${isCompleted ? 'bg-slate-300' : 'bg-green-500'} rounded-full border-2 border-white`} />
              </div>
              <div>
                <h2 className="font-bold text-slate-800 tracking-tight">{currentBooking.doctorName}</h2>
                <div className="flex items-center space-x-2">
                  <Badge variant="secondary" className="bg-slate-200/50 text-slate-600 text-[10px] uppercase font-bold">{currentBooking.specialty}</Badge>
                  <span className={`text-xs font-bold uppercase tracking-tighter ${isCompleted ? 'text-slate-400' : 'text-green-600'}`}>
                    {isCompleted ? 'Offline' : 'Online'}
                  </span>
                </div>
              </div>
            </div>
            {!isCompleted ? (
              <div className="flex space-x-2">
                <Button variant="outline" className="gap-2 text-slate-600 border-slate-200 bg-white/50"><Phone size={16} /> Audio</Button>
                <Button onClick={handleEndConsultation} variant="destructive" className="rounded-full px-6 font-bold text-xs uppercase tracking-wider">End Consultation</Button>
              </div>
            ) : (
              <Badge className="bg-blue-100 text-blue-700 px-4 py-1.5 rounded-full border-none">Session Closed</Badge>
            )}
          </div>

          <div className="flex-1 overflow-y-auto p-6 space-y-6">
            {messages.map((msg) => (
              <div key={msg.id} className={`flex ${msg.sender === "patient" ? "justify-end" : "justify-start"}`}>
                {msg.sender === "system" ? (
                  <div className="w-full bg-slate-100/80 border border-slate-200/50 rounded-xl p-4 text-center text-[12px] whitespace-pre-wrap font-bold text-slate-600 uppercase tracking-wide italic shadow-sm leading-relaxed">{msg.content}</div>
                ) : (
                  <div className={`max-w-[75%] px-4 py-3 rounded-2xl shadow-sm relative group ${
                    msg.sender === "patient" ? "bg-teal-500 text-white rounded-tr-none" : "bg-white/90 border border-slate-100 text-slate-800 rounded-tl-none"
                  }`}>
                    <p className="text-[15px] leading-relaxed">{msg.content}</p>
                    <div className={`flex items-center justify-end mt-1.5 space-x-1 text-[10px] ${msg.sender === "patient" ? "text-teal-100" : "text-slate-400"}`}>
                      <span>{formatTime(msg.timestamp)}</span>
                    </div>
                  </div>
                )}
              </div>
            ))}
            {isTyping && <div className="flex justify-start italic text-xs text-slate-500 ml-2 animate-pulse font-medium">Assistant is typing...</div>}
            <div ref={messagesEndRef} />
          </div>

          <div className="p-4 bg-white/40 backdrop-blur-md border-t border-slate-200/50">
            <form onSubmit={sendMessage} className="flex items-center space-x-2 bg-white/80 p-1.5 rounded-2xl border border-slate-200 shadow-sm">
              <Button type="button" onClick={() => handleQuickAction("Upload Images")} variant="ghost" size="icon" className="text-slate-400" disabled={isCompleted}><Paperclip size={20} /></Button>
              <Input
                disabled={isCompleted}
                placeholder={isCompleted ? "This consultation has ended." : "Describe your symptoms..."}
                className="border-none bg-transparent shadow-none focus-visible:ring-0 text-[15px]"
                value={message}
                onChange={(e) => setMessage(e.target.value)}
              />
              <Button type="submit" size="icon" className="bg-teal-500 hover:bg-teal-600 rounded-xl" disabled={!message.trim() || isCompleted}><Send size={18} /></Button>
            </form>
          </div>
        </div>

        {/* Sidebar */}
        <aside className="w-[340px] p-6 hidden xl:block space-y-6 overflow-y-auto">
          <Card className="border-none shadow-sm rounded-2xl overflow-hidden bg-white/70 backdrop-blur-md">
            <CardHeader className="bg-white/50 pb-3">
              <CardTitle className="text-sm font-bold uppercase tracking-wider text-slate-400 flex items-center gap-2">
                <Clock size={14} /> Consultation Details
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 pt-2">
              <SidebarRow label="Booking ID" value={currentBooking.id.substring(0, 10)} />
              <SidebarRow label="Patient" value={currentBooking.patientName} />
              <SidebarRow label="Location" value={currentBooking.location} />
              <SidebarRow label="Scheduled" value={currentBooking.time} />
              <SidebarRow label="Duration" value={`${duration} mins`} highlighted={!isCompleted} />
              <Separator className="bg-slate-200/50" />
              <div className="flex justify-between items-center">
                <span className="text-sm font-medium text-slate-500">Consultation Fee:</span>
                <span className="text-xl font-black text-blue-600">{currentBooking.fee}</span>
              </div>
            </CardContent>
          </Card>

          {isCompleted && (
            <Card className="border-none shadow-lg rounded-2xl bg-teal-600 text-white animate-in slide-in-from-bottom-4 duration-500">
              <CardHeader className="pb-2">
                <CardTitle className="text-[10px] font-black uppercase tracking-[0.2em] opacity-80 flex items-center gap-2">
                  <Calendar size={14} /> Next Upcoming Appointment
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <h3 className="text-lg font-bold leading-tight">{nextBookingData.doctorName}</h3>
                  <div className="flex items-center gap-1 opacity-90 text-[10px] font-bold uppercase mt-1">
                    <MapPin size={10} /> {nextBookingData.location}
                  </div>
                </div>
                <div className="bg-white/10 rounded-xl p-3 border border-white/10">
                  <p className="text-[10px] uppercase font-black opacity-60 mb-0.5 tracking-wider">Date & Time</p>
                  <p className="text-sm font-bold">{nextBookingData.date} • {nextBookingData.time}</p>
                </div>
                <Button 
                  onClick={handleStartNextConsultation}
                  className="w-full bg-white text-teal-600 hover:bg-slate-100 font-bold text-xs uppercase h-10 rounded-xl shadow-md"
                >
                  Start Conversation
                </Button>
              </CardContent>
            </Card>
          )}

          <Card className="border-none shadow-sm rounded-2xl bg-white/70 backdrop-blur-md">
            <CardHeader className="bg-white/50 pb-3">
              <CardTitle className="text-sm font-bold uppercase tracking-wider text-slate-400">
                {isCompleted ? "Consultation Assets" : "Quick Actions"}
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 pt-2">
              <input 
                type="file" 
                ref={fileInputRef} 
                className="hidden" 
                accept="image/*"
                onChange={handleFileUpload}
              />
              
              <ActionButton 
                icon={<FileText size={16} />} 
                label={isCompleted ? "Download Summary" : "Share Medical History"} 
                onClick={() => handleQuickAction(isCompleted ? "Download Summary" : "Share Medical History")} 
              />
              <ActionButton 
                icon={<Image size={16} />} 
                label={isCompleted ? "View Clinical Notes" : "Upload Images"} 
                onClick={() => handleQuickAction(isCompleted ? "View Clinical Notes" : "Upload Images")} 
              />
              {!isCompleted && <ActionButton icon={<FileText size={16} />} label="Request Prescription" onClick={() => handleQuickAction("Request Prescription")} />}
            </CardContent>
          </Card>
        </aside>
      </main>
    </div>
  );
};

// --- Helper Components ---
const SidebarRow = ({ label, value, highlighted = false }: { label: string, value: string, highlighted?: boolean }) => (
  <div className="flex justify-between items-center">
    <span className="text-sm text-slate-400 font-medium">{label}:</span>
    <span className={`text-sm font-bold ${highlighted ? "text-teal-600" : "text-slate-700"}`}>{value}</span>
  </div>
);

const ActionButton = ({ icon, label, onClick }: { icon: any, label: string, onClick: () => void }) => (
  <Button variant="ghost" className="w-full justify-start text-slate-600 hover:bg-white/80 h-11 px-3 border border-slate-200/50 rounded-xl bg-white/30" onClick={onClick}>
    <span className="mr-3 opacity-60">{icon}</span>
    <span className="text-xs font-bold">{label}</span>
  </Button>
);

export default Consultation;